spring.application.name=auth-service
logging.level.root=INFO
logging.level.com.petclinic.adminservice=DEBUG
logging.file.name=logs/service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
management.endpoints.web.base-path=/actuator
management.server.port=8081