server:
  port: 8084

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true
    username: root
    password: Yash@2002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always